# 官方文档：https://docs.spring.io/spring-cloud-gateway/docs/4.0.0/reference/html/
#         https://docs.spring.io/spring-boot/docs/3.0.2/reference/html/features.html#features.external-config

# profile 环境文件中的配置 会覆盖主配置文件中的同名字段。

# 踩坑记录：
# 报错1：Client not connected, current status:STARTING
# 是因为服务器的防火墙没有打开 9848、9849 这两个端口
# 报错2：读取不到配置中心的配置
# 是因为 配置中心的 "Data Id" 的值，必须带文件类型后缀，比如：cloud-application-gateway.properties


# 详解Nacos和Eureka的区别：https://blog.csdn.net/weixin_43776652/article/details/120874245



# 如果 application.properties 和 application.yml 中有相同的配置，以 application.properties 的为准
debug: false


server:
  port: 8080


# 打印 某些功能 的 某个级别的 日志
logging:
  level:
#    org.springframework.cloud.gateway: debug
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client.ContextAwareHttpClientMetricsRecorder: debug
#    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG



spring:
  application:
    name: cloud-application-gateway  #  本应用的名称
  profiles:
    active: dev



