driver=com.mysql.jdbc.Driver
url=jdbc:mysql://192.168.124.10:3306/JavaWeb
user=root
password=feng234800
#UserDao=com.itheima.dao.MySqlUserDao
UserDao=com.itheima.dao.MySqlUserDao2
#UserDao=com.itheima.dao.XmlUserDao