# 如果 application.properties 和 application.yml 中有相同的配置，以 application.properties 的为准
# 官方文档，讲解了所有配置属性
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/


spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fengshiqing?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root

  data:
    redis: # dev 环境用的单机模式，必须这么配
      host: 123
      port: 123 # Redis服务器连接密码（默认为空）
      password: 123 # Redis服务器连接密码（默认为空）


  ai:
    dashscope:
      api-key: ${dashscope_api_key}  # 替换为你的真实 API Key
      chat:
        options:
          model: qwen-plus-2025-12-01

    vectorstore:
      milvus:
        client:
          host: "localhost" # default: localhost
          port: 19530 # default: 19530
          username: "" # default: root
          password: "" # default: milvus
        databaseName: "default"
        collectionName: "vector_store" # default: vector_store
        embeddingDimension: 1536 # default: 1536
        indexType: IVF_FLAT # default: IVF_FLAT
        metricType: COSINE # default: COSINE
        initializeSchema: true # 自动创建集合

    # 网络搜索功能
    websearch:
      api-key: ${kinghy.ai.websearch.api-key:123456}
      searxng:
        url: "http://127.0.0.1:8080/search"
        nums: 10
        engines: "duckduckgo,google,bing,brave,mojeek,presearch,qwant,startpage,yahoo,arxiv,crossref,google_scholar,internetarchivescholar,semantic_scholar"



# 腾讯云服务相关的配置项，后续所有涉及到 腾讯公司的服务，都需要在这里进行配置
tencent:
  # 腾讯云对象存储（Cloud Object Storage，COS）用到的配置项
  cos:
    secret-id: 123                       # API 密钥ID
    secret-key: 123                          # API 密钥KEY
    region: ap-shanghai                                                   # 存储桶所属地域
    bucket-name: 123                              # 存储桶空间名称
    url: https://tc-test-neps-cos.cos.ap-shanghai.myqcloud.com # 存储桶访问域名
    prefix: /123/  # 所有的文件都是放在 /fpc/ 下的。上传文件时，路劲不存在时会自动创建的。
    prefix-temp: /123/temp/  # 临时文件放在 /fpc/temp/ 下。后续可以加个定时任务，删除临时文件

