# \u5B98\u65B9\u6587\u6863\uFF0C\u8BB2\u89E3\u4E86\u6240\u6709\u914D\u7F6E\u5C5E\u6027
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/

# \u5F00\u542Fdebug\u6A21\u5F0F\uFF0C\u6253\u5370debug\u65E5\u5FD7\uFF1Atrue\u5F00\u542F\u3001false\u5173\u95ED
debug=false


server.port=8888
server.servlet.context-path=/ai

# \u5E94\u7528\u540D\u79F0
spring.application.name=AiApplication
spring.profiles.active=dev


# \u4E0A\u4F20\u6587\u4EF6\uFF08\u5B98\u65B9\u6587\u6863\u4E2D\u641C\u7D22 multipart\uFF09\uFF1A
# maxFileSize \u662F\u5355\u4E2A\u6587\u4EF6\u5927\u5C0F
# maxRequestSize\u662F\u8BBE\u7F6E\u603B\u4E0A\u4F20\u7684\u6570\u636E\u5927\u5C0F
# \u5355\u4F4D\u53EA\u80FD\u662FMB\u548CKB\u4E24\u79CD\u7C7B\u578B\uFF0C\u5B57\u6BCD\u5927\u5C0F\u5199\u968F\u610F\uFF0C\u6570\u5B57\u662FLong\u7C7B\u578B\uFF0C-1\u8868\u793A\u65E0\u9650\u5236
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


mybatis.mapper-locations=classpath:mapper/*.xml


# deepseek \u7684 API key \u5BC6\u94A5\uFF0C\u8FD9\u4E2A\u8981\u82B1\u94B1\u7684\uFF0C\u5FC5\u987B\u914D\u7F6E\u5230\u73AF\u5883\u53D8\u91CF\u4E2D
#spring.ai.deepseek.base-url=https://api.deepseek.com  # DeepSeekConnectionProperties \u8FD9\u91CC\u5DF2\u7ECF\u660E\u786E\u8BBE\u7F6E\u8FC7\u4E86\uFF0C\u5C31\u4E0D\u7528\u518D\u6B21\u5199\u4E86\u3002
spring.ai.deepseek.api-key=${deepseek_api_key}
# \u63A5\u53E3\u6587\u6863\uFF08\u5B98\u65B9\u7684\uFF09\u770B\u8FD9\u91CC\uFF1Ahttps://api-docs.deepseek.com/zh-cn/

spring.ai.deepseek.chat.options.model=deepseek-chat


spring.ai.openai.api-key=${openai_api_key}
spring.ai.openai.base-url=https://api.deepseek.com/v1
spring.ai.openai.chat.options.model=deepseek-chat
spring.ai.openai.chat.options.temperature=0.7



# \u5065\u5EB7\u68C0\u67E5\u914D\u7F6E
# \u663E\u793A\u8BE6\u7EC6\u7684\u5065\u5EB7\u68C0\u67E5\u7EC4\u4EF6\u4FE1\u606F\uFF08details / components\uFF09\u3002\u9ED8\u8BA4 never\uFF0C\u53EA\u663E\u793A "{ "status": "UP" }"
management.endpoint.health.show-details=always
