server:
  port: 8989
  servlet:
    context-path: /api/v1

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: dev



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fengshiqing.springai.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



aliyun:
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: ${alioss.access-key-id}
    access-key-secret: ${alioss.access-key-secret}
    bucket-name: xushu-rag



xushu:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: xushu
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: xushu
    user-ttl: 7200000
    user-token-name: authorization



logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug
