# 如果 application.properties 和 application.yml 中有相同的配置，以 application.properties 的为准
server:
  port: 8080


# 自定义 starter 中的属性
spring:
  custom:
    name: 冯仕清

  redis:
    host: 192.168.10.100
    port: 6379 # Redis服务器连接密码（默认为空）
    password:  # Redis服务器连接密码（默认为空）
    database: 0 # Redis数据库索引（默认为0）
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制），默认 8
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制），默认 -1
        max-idle: 8  # 连接池中的最大空闲连接，默认 8
        min-idle: 1  # 连接池中的最小空闲连接，默认 0
    timeout: 3000  # 连接超时时间（毫秒）

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.100:8848
      config:
        server-addr: 192.168.10.100:8848