# 配置根级别的日志为:info，输出的位置有两个：appender1、appender2
log4j.rootLogger = info,appender1,appender2

#此包下的日志级别为:TRACE
log4j.logger.com.mybatis=TRACE

# appender1位置表示：输出到控制台
log4j.appender.appender1 = org.apache.log4j.ConsoleAppender 

# appender2位置表示：输出到文件，只是表示输出到文件，具体到哪个文件需要配置：在D:/log4j.log文件里
log4j.appender.appender2 = org.apache.log4j.FileAppender 
log4j.appender.appender2.File = D:/logs/log4j.log

#配置输出的格式
log4j.appender.appender1.layout = org.apache.log4j.TTCCLayout
log4j.appender.appender2.layout = org.apache.log4j.TTCCLayout
